# Generated by Django 3.0.7 on 2020-06-20 20:12

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cesta', models.CharField(max_length=100)),
                ('preco_cesta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/felipe/dev/VirtualShop/mymarket/website/static/images'), upload_to='')),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=120, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('al', 'Alagoas'), ('am', 'Amazonas'), ('ap', 'Amapá'), ('ba', 'Bahia'), ('ce', 'Ceará'), ('df', 'Distrito Federal'), ('es', 'Espírito Santo'), ('go', 'Goiás'), ('ma', 'Maranhão'), ('mt', 'Mato Grosso'), ('ms', 'Mato Grosso do Sul'), ('mg', 'Minas Gerais'), ('pa', 'Pará'), ('pb', 'Paraíba'), ('pr', 'Paraná'), ('pe', 'Pernambuco'), ('pi', 'Piauí'), ('rj', 'Rio de Janeiro'), ('rn', 'Rio Grande do Norte'), ('ro', 'Rondônia'), ('rs', 'Rio Grande do Sul'), ('rr', 'Roraima'), ('sc', 'Santa Catarina'), ('se', 'Sergipe'), ('sp', 'São Paulo'), ('to', 'Tocantins')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=120)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_desconto', models.CharField(max_length=20)),
                ('preco_desc', models.IntegerField()),
                ('imagem_oferta', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/felipe/dev/VirtualShop/mymarket/website/static/images'), upload_to='')),
                ('data_desc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('est_cad', models.CharField(max_length=1)),
                ('senha', models.CharField(max_length=150)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, unique=True)),
                ('numero2', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/felipe/dev/VirtualShop/mymarket/website/static/images'), upload_to='')),
                ('obs', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/felipe/dev/VirtualShop/mymarket/website/static/images'), upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Categoria')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Oferta')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Telefone'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=20)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor_produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Telefone'),
        ),
        migrations.CreateModel(
            name='Endereco_fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Endereco')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cesta_produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Cesta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Cidade'),
        ),
    ]
